name: Build Electron App

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Make Electron app
        run: npm run make

      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: vox-app-${{ matrix.os }}
          path: out/make/**
